// ============================================
// Lucky Charms — Definitions & Synergies
// Sprint 2: Expanded to ~50 charms, ~20 synergies
// ============================================
import { CharmDefinition, SynergyDefinition } from './types';

export const ALL_CHARMS: CharmDefinition[] = [
  // ====== COMMON (10) ======
  {
    id: 'penny-pincher',
    name: 'Penny Pincher',
    rarity: 'Common',
    description: 'Reduce rent you pay by 15%.',
    icon: '💰',
    trigger: 'ON_PAY_RENT',
    stackable: false,
    cost: 75,
    sellValue: 30,
    synergyTags: ['economy', 'defense'],
  },
  {
    id: 'swift-feet',
    name: 'Swift Feet',
    rarity: 'Common',
    description: 'Roll an extra +1 to your dice total.',
    icon: '👟',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 80,
    sellValue: 35,
    synergyTags: ['movement', 'dice'],
  },
  {
    id: 'toll-booth',
    name: 'Toll Booth',
    rarity: 'Common',
    description: 'Earn 10% extra on rent you collect.',
    icon: '🚧',
    trigger: 'ON_RECEIVE_RENT',
    stackable: false,
    cost: 80,
    sellValue: 35,
    synergyTags: ['income', 'rent'],
  },
  {
    id: 'lucky-penny',
    name: 'Lucky Penny',
    rarity: 'Common',
    description: 'Gain 25 coins at the start of each turn.',
    icon: '🪙',
    trigger: 'ON_TURN_START',
    stackable: true,
    cost: 60,
    sellValue: 25,
    synergyTags: ['income', 'passive'],
    upgradeable: true,
    maxLevel: 3,
    upgradeDescriptions: ['Gain 40 coins/turn.', 'Gain 60 coins/turn.'],
  },
  {
    id: 'bargain-hunter',
    name: 'Bargain Hunter',
    rarity: 'Common',
    description: '10% discount on property purchases.',
    icon: '🏷️',
    trigger: 'ON_BUY_PROPERTY',
    stackable: false,
    cost: 70,
    sellValue: 30,
    synergyTags: ['economy', 'purchase'],
  },
  {
    id: 'rent-rebate',
    name: 'Rent Rebate',
    rarity: 'Common',
    description: 'Whenever you pay rent, recover 15% from the Bank.',
    icon: '🧾',
    trigger: 'ON_PAY_RENT',
    stackable: false,
    cost: 85,
    sellValue: 35,
    synergyTags: ['economy', 'defense'],
  },
  {
    id: 'landlords-grin',
    name: "Landlord's Grin",
    rarity: 'Common',
    description: 'When another player lands on your property, gain 20 extra coins.',
    icon: '😏',
    trigger: 'ON_RECEIVE_RENT',
    stackable: false,
    cost: 75,
    sellValue: 30,
    synergyTags: ['income', 'rent'],
  },
  {
    id: 'the-accountant',
    name: 'The Accountant',
    rarity: 'Common',
    description: 'At end of each round, gain 10 coins per property you own.',
    icon: '📊',
    trigger: 'ON_ROUND_END',
    stackable: false,
    cost: 90,
    sellValue: 35,
    synergyTags: ['income', 'property'],
    upgradeable: true,
    maxLevel: 3,
    upgradeDescriptions: ['15 coins per property.', '25 coins per property.'],
  },
  {
    id: 'lucky-seven',
    name: 'Lucky Seven',
    rarity: 'Common',
    description: 'Rolling exactly 7 grants 100 bonus coins.',
    icon: '7️⃣',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 70,
    sellValue: 30,
    synergyTags: ['dice', 'luck'],
  },
  {
    id: 'loaded-pocket',
    name: 'Loaded Pocket',
    rarity: 'Common',
    description: 'You may reroll one die once per turn (auto: keeps the higher total).',
    icon: '🎯',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 90,
    sellValue: 40,
    synergyTags: ['dice', 'control'],
  },

  // ====== UNCOMMON (10) ======
  {
    id: 'shield-charm',
    name: 'Shield Charm',
    rarity: 'Uncommon',
    description: 'Once per game, block a rent payment entirely.',
    icon: '🛡️',
    trigger: 'ON_PAY_RENT',
    stackable: false,
    cost: 150,
    sellValue: 60,
    synergyTags: ['defense', 'survival'],
  },
  {
    id: 'tax-haven',
    name: 'Tax Haven',
    rarity: 'Uncommon',
    description: 'Tax payments are halved.',
    icon: '🏝️',
    trigger: 'ON_TAX',
    stackable: false,
    cost: 120,
    sellValue: 50,
    synergyTags: ['economy', 'defense'],
  },
  {
    id: 'golden-passport',
    name: 'Golden Passport',
    rarity: 'Uncommon',
    description: 'Collect 50 extra coins when passing Start.',
    icon: '📜',
    trigger: 'ON_PASS_START',
    stackable: true,
    cost: 130,
    sellValue: 55,
    synergyTags: ['income', 'movement'],
    upgradeable: true,
    maxLevel: 3,
    upgradeDescriptions: ['75 extra coins.', '100 extra coins.'],
  },
  {
    id: 'snake-eyes',
    name: 'Snake Eyes',
    rarity: 'Uncommon',
    description: 'Rolling doubles gives you 75 bonus coins.',
    icon: '🐍',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 140,
    sellValue: 55,
    synergyTags: ['dice', 'income'],
  },
  {
    id: 'golden-boot',
    name: 'Golden Boot',
    rarity: 'Uncommon',
    description: 'Movement is increased by 2.',
    icon: '🥾',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 130,
    sellValue: 55,
    synergyTags: ['movement', 'dice'],
  },
  {
    id: 'tax-evasion',
    name: 'Tax Evasion',
    rarity: 'Uncommon',
    description: 'The first tax payment every round is reduced by 50%.',
    icon: '🕶️',
    trigger: 'ON_TAX',
    stackable: false,
    cost: 130,
    sellValue: 55,
    synergyTags: ['economy', 'defense'],
  },
  {
    id: 'property-flipper',
    name: 'Property Flipper',
    rarity: 'Uncommon',
    description: 'Properties you sell fetch 25% more money.',
    icon: '🔄',
    trigger: 'ON_SELL_PROPERTY',
    stackable: false,
    cost: 120,
    sellValue: 50,
    synergyTags: ['economy', 'property'],
  },
  {
    id: 'bank-error-charm',
    name: 'Bank Error',
    rarity: 'Uncommon',
    description: 'Occasionally receive a random 50-150 coin payment from the Bank at turn start.',
    icon: '🏦',
    trigger: 'ON_TURN_START',
    stackable: false,
    cost: 110,
    sellValue: 45,
    synergyTags: ['income', 'luck'],
  },
  {
    id: 'bad-investment',
    name: 'Bad Investment',
    rarity: 'Uncommon',
    description: 'Properties worth 120 coins or less generate triple rent.',
    icon: '📉',
    trigger: 'ON_RECEIVE_RENT',
    stackable: false,
    cost: 140,
    sellValue: 55,
    synergyTags: ['rent', 'cheap-property'],
  },
  {
    id: 'parasite',
    name: 'Parasite',
    rarity: 'Uncommon',
    description: 'Whenever another player completes a group, steal 10% of its total value.',
    icon: '🦠',
    trigger: 'ON_BUY_PROPERTY',
    stackable: false,
    cost: 150,
    sellValue: 60,
    synergyTags: ['theft', 'economy'],
  },

  // ====== RARE (10) ======
  {
    id: 'property-magnet',
    name: 'Property Magnet',
    rarity: 'Rare',
    description: '25% discount on property purchases.',
    icon: '🧲',
    trigger: 'ON_BUY_PROPERTY',
    stackable: false,
    cost: 200,
    sellValue: 80,
    synergyTags: ['purchase', 'economy'],
  },
  {
    id: 'double-or-nothing',
    name: 'Double or Nothing',
    rarity: 'Rare',
    description: 'Doubles on dice give you 100 bonus coins.',
    icon: '🎰',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 220,
    sellValue: 90,
    synergyTags: ['dice', 'income'],
  },
  {
    id: 'loaded-dice',
    name: 'Loaded Dice',
    rarity: 'Rare',
    description: 'Every third dice roll, your total is increased by 3.',
    icon: '🎲',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 210,
    sellValue: 85,
    synergyTags: ['dice', 'control'],
    upgradeable: true,
    maxLevel: 2,
    upgradeDescriptions: ['Every second roll is boosted by 3.'],
  },
  {
    id: 'monopoly-monopoly',
    name: 'Monopoly Monopoly',
    rarity: 'Rare',
    description: 'If you own a complete property group, its rent is +50%.',
    icon: '🏘️',
    trigger: 'ON_RECEIVE_RENT',
    stackable: false,
    cost: 250,
    sellValue: 100,
    synergyTags: ['rent', 'property', 'set-bonus'],
  },
  {
    id: 'double-down',
    name: 'Double Down',
    rarity: 'Rare',
    description: 'All financial events (rent paid/received, taxes) are doubled. Win big or lose big.',
    icon: '⚡',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 200,
    sellValue: 80,
    synergyTags: ['risk', 'economy'],
  },
  {
    id: 'phantom-deed',
    name: 'Phantom Deed',
    rarity: 'Rare',
    description: 'Treat one random unowned property as temporarily yours for set bonuses.',
    icon: '👻',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 250,
    sellValue: 100,
    synergyTags: ['property', 'set-interference'],
  },
  {
    id: 'colour-shift',
    name: 'Colour Shift',
    rarity: 'Rare',
    description: 'One of your properties counts toward an adjacent colour group as well.',
    icon: '🌈',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 240,
    sellValue: 95,
    synergyTags: ['property', 'set-interference'],
  },
  {
    id: 'upgrade-discount',
    name: 'Cheap Labour',
    rarity: 'Rare',
    description: 'Property upgrades cost 30% less.',
    icon: '🔨',
    trigger: 'ON_UPGRADE_PROPERTY',
    stackable: false,
    cost: 200,
    sellValue: 80,
    synergyTags: ['economy', 'property'],
  },
  {
    id: 'rent-freeze-charm',
    name: 'Frost Shield',
    rarity: 'Rare',
    description: 'The first rent you pay each round is halved.',
    icon: '❄️',
    trigger: 'ON_PAY_RENT',
    stackable: false,
    cost: 220,
    sellValue: 90,
    synergyTags: ['defense', 'rent'],
  },
  {
    id: 'lucky-charm',
    name: 'Lucky Charm',
    rarity: 'Rare',
    description: 'All other charms you own are slightly stronger (+10% to numerical effects).',
    icon: '🍀',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 280,
    sellValue: 110,
    synergyTags: ['meta', 'amplify'],
  },

  // ====== EPIC (8) ======
  {
    id: 'rent-lord',
    name: 'Rent Lord',
    rarity: 'Epic',
    description: 'All your rents are doubled.',
    icon: '👑',
    trigger: 'ON_RECEIVE_RENT',
    stackable: false,
    cost: 400,
    sellValue: 160,
    synergyTags: ['rent', 'income'],
    upgradeable: true,
    maxLevel: 3,
    upgradeDescriptions: ['Rents are tripled.', 'Rents are quadrupled.'],
  },
  {
    id: 'second-chance',
    name: 'Second Chance',
    rarity: 'Epic',
    description: 'When you would go bankrupt, survive with 200 coins once.',
    icon: '💫',
    trigger: 'ON_BANKRUPTCY',
    stackable: false,
    cost: 350,
    sellValue: 140,
    synergyTags: ['survival', 'defense'],
  },
  {
    id: 'the-parasite-estate',
    name: 'The Parasite Estate',
    rarity: 'Epic',
    description: '5% of ALL rent generated on the board flows to you.',
    icon: '🕸️',
    trigger: 'ON_PAY_RENT',
    stackable: false,
    cost: 400,
    sellValue: 160,
    synergyTags: ['income', 'theft'],
  },
  {
    id: 'time-traveller',
    name: 'Time Traveller',
    rarity: 'Epic',
    description: 'Once per game, undo your last movement (return to previous position).',
    icon: '⏳',
    trigger: 'ACTIVE',
    stackable: false,
    cost: 350,
    sellValue: 140,
    synergyTags: ['movement', 'control'],
  },
  {
    id: 'set-thief',
    name: 'Set Thief',
    rarity: 'Epic',
    description: 'Steal the set-completion bonus from one opponent (they lose it, you gain it).',
    icon: '🦊',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 380,
    sellValue: 150,
    synergyTags: ['theft', 'set-interference'],
  },
  {
    id: 'bankruptcy-clause',
    name: 'Bankruptcy Clause',
    rarity: 'Epic',
    description: 'First time you\'d go bankrupt, survive with 10% of your previous wealth.',
    icon: '📋',
    trigger: 'ON_BANKRUPTCY',
    stackable: false,
    cost: 320,
    sellValue: 130,
    synergyTags: ['survival', 'defense'],
  },
  {
    id: 'charm-amplifier',
    name: 'Charm Amplifier',
    rarity: 'Epic',
    description: 'Unlock +1 charm slot.',
    icon: '🔮',
    trigger: 'PASSIVE',
    stackable: true,
    cost: 350,
    sellValue: 140,
    synergyTags: ['meta', 'slots'],
  },
  {
    id: 'golden-touch',
    name: 'Golden Touch',
    rarity: 'Epic',
    description: 'The first property you buy each round costs 50% less.',
    icon: '✋',
    trigger: 'ON_BUY_PROPERTY',
    stackable: false,
    cost: 360,
    sellValue: 145,
    synergyTags: ['purchase', 'economy'],
  },

  // ====== LEGENDARY (5) ======
  {
    id: 'midas-touch',
    name: 'Midas Touch',
    rarity: 'Legendary',
    description: 'Every property you own generates 30 coins at round end.',
    icon: '✨',
    trigger: 'ON_ROUND_END',
    stackable: false,
    cost: 600,
    sellValue: 250,
    synergyTags: ['income', 'property'],
    upgradeable: true,
    maxLevel: 3,
    upgradeDescriptions: ['45 coins per property.', '60 coins per property.'],
  },
  {
    id: 'crown-jewel',
    name: 'Crown Jewel',
    rarity: 'Legendary',
    description: 'Your most expensive property generates 5x normal rent.',
    icon: '💎',
    trigger: 'ON_RECEIVE_RENT',
    stackable: false,
    cost: 650,
    sellValue: 270,
    synergyTags: ['rent', 'premium'],
  },
  {
    id: 'fate-weaver',
    name: 'Fate Weaver',
    rarity: 'Legendary',
    description: 'Random events always resolve in your favour.',
    icon: '🌌',
    trigger: 'ON_EVENT',
    stackable: false,
    cost: 700,
    sellValue: 290,
    synergyTags: ['luck', 'control'],
  },
  {
    id: 'empire-builder',
    name: 'Empire Builder',
    rarity: 'Legendary',
    description: 'Completing a property set immediately upgrades all its properties to Shop tier.',
    icon: '🏗️',
    trigger: 'ON_BUY_PROPERTY',
    stackable: false,
    cost: 600,
    sellValue: 250,
    synergyTags: ['property', 'set-bonus'],
  },
  {
    id: 'rubber-baron',
    name: 'Rubber Baron',
    rarity: 'Legendary',
    description: 'Gain 1 coin for every coin any opponent spends (rent, tax, purchases).',
    icon: '🎩',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 750,
    sellValue: 310,
    synergyTags: ['income', 'theft'],
  },

  // ====== CURSED (7) ======
  {
    id: 'greedy-goblin',
    name: 'Greedy Goblin',
    rarity: 'Cursed',
    description: 'Triple your rent income, but pay 50 coins per turn upkeep.',
    icon: '👺',
    trigger: 'ON_RECEIVE_RENT',
    stackable: false,
    cost: 250,
    sellValue: 100,
    synergyTags: ['rent', 'risk'],
  },
  {
    id: 'chaos-dice',
    name: 'Chaos Dice',
    rarity: 'Cursed',
    description: 'Dice rolls are wilder (each die rerolled randomly). Unpredictable!',
    icon: '🎲',
    trigger: 'ON_DICE_ROLL',
    stackable: false,
    cost: 180,
    sellValue: 70,
    synergyTags: ['dice', 'chaos'],
  },
  {
    id: 'debt-collector',
    name: 'Debt Collector',
    rarity: 'Cursed',
    description: '+50% rent income. BUT you pay double rent on opponents\' properties.',
    icon: '💀',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 200,
    sellValue: 80,
    synergyTags: ['rent', 'risk'],
  },
  {
    id: 'golden-handcuffs',
    name: 'Golden Handcuffs',
    rarity: 'Cursed',
    description: 'Property income is doubled. BUT you cannot sell properties.',
    icon: '⛓️',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 220,
    sellValue: 90,
    synergyTags: ['rent', 'restriction'],
  },
  {
    id: 'all-in',
    name: 'All In',
    rarity: 'Cursed',
    description: 'All rent gained is doubled. BUT all taxes are doubled.',
    icon: '♠️',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 200,
    sellValue: 80,
    synergyTags: ['rent', 'risk', 'economy'],
  },
  {
    id: 'the-gambler',
    name: 'The Gambler',
    rarity: 'Cursed',
    description: 'Each turn: 25% chance of +300 coins, 25% chance of -200 coins.',
    icon: '🃏',
    trigger: 'ON_TURN_START',
    stackable: false,
    cost: 180,
    sellValue: 70,
    synergyTags: ['luck', 'risk', 'income'],
  },
  {
    id: 'house-of-cards',
    name: 'House of Cards',
    rarity: 'Cursed',
    description: 'Upgrades cost 40% less. BUT each time you pass Start, one random upgrade may vanish.',
    icon: '🏚️',
    trigger: 'PASSIVE',
    stackable: false,
    cost: 160,
    sellValue: 65,
    synergyTags: ['economy', 'risk', 'property'],
  },
];

// ====== SYNERGIES (20) ======
export const SYNERGIES: SynergyDefinition[] = [
  // --- Original 4 ---
  {
    id: 'money-machine',
    name: 'Money Machine',
    requiredCharmIds: ['penny-pincher', 'toll-booth', 'lucky-penny'],
    description: 'Earn 100 bonus coins every turn and halve all rent payments.',
    icon: '🏦',
  },
  {
    id: 'fortified-fortune',
    name: 'Fortified Fortune',
    requiredCharmIds: ['shield-charm', 'second-chance'],
    description: 'Shield regenerates every 3 turns. Bankruptcy protection triggers twice.',
    icon: '🏰',
  },
  {
    id: 'golden-empire',
    name: 'Golden Empire',
    requiredCharmIds: ['rent-lord', 'midas-touch'],
    description: 'Properties generate 60 coins each at round end and rent is tripled.',
    icon: '🌟',
  },
  {
    id: 'cursed-gambler',
    name: 'Cursed Gambler',
    requiredCharmIds: ['greedy-goblin', 'chaos-dice'],
    description: 'No upkeep cost! Rent income is quadrupled but dice are wilder.',
    icon: '🃏',
  },
  // --- New 16 ---
  {
    id: 'rigged-casino',
    name: 'Rigged Casino',
    requiredCharmIds: ['loaded-dice', 'lucky-seven', 'snake-eyes'],
    description: 'All dice-related charms are 50% stronger. "The house always wins."',
    icon: '🎰',
  },
  {
    id: 'rent-tank',
    name: 'Rent Tank',
    requiredCharmIds: ['rent-rebate', 'landlords-grin'],
    description: 'Recover 30% of rent paid and earn 50 extra when collecting rent.',
    icon: '🛢️',
  },
  {
    id: 'budget-empire',
    name: 'Budget Empire',
    requiredCharmIds: ['bad-investment', 'property-flipper'],
    description: 'Cheap properties (≤120c) generate 4x rent. Selling gives 50% more.',
    icon: '🏚️',
  },
  {
    id: 'tax-ghost',
    name: 'Tax Ghost',
    requiredCharmIds: ['tax-haven', 'tax-evasion'],
    description: 'You pay zero taxes. "I don\'t even exist."',
    icon: '👻',
  },
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    requiredCharmIds: ['swift-feet', 'golden-boot'],
    description: 'Movement +4 total. Passing Start gives 100 extra coins.',
    icon: '💨',
  },
  {
    id: 'phantom-monopoly',
    name: 'Phantom Monopoly',
    requiredCharmIds: ['phantom-deed', 'colour-shift'],
    description: 'Your phantom property becomes permanent until sold. Double set bonus.',
    icon: '🔮',
  },
  {
    id: 'survival-instinct',
    name: 'Survival Instinct',
    requiredCharmIds: ['second-chance', 'bankruptcy-clause'],
    description: 'Bankruptcy protection triggers 3 times. You\'re nearly unkillable.',
    icon: '🐱',
  },
  {
    id: 'property-vacuum',
    name: 'Property Vacuum',
    requiredCharmIds: ['property-magnet', 'bargain-hunter'],
    description: '35% discount on all purchases. You buy properties for pennies.',
    icon: '🌀',
  },
  {
    id: 'dice-master',
    name: 'Dice Master',
    requiredCharmIds: ['loaded-pocket', 'double-or-nothing'],
    description: 'Reroll both dice once per turn. Doubles always give 200 bonus coins.',
    icon: '🎯',
  },
  {
    id: 'income-empire',
    name: 'Income Empire',
    requiredCharmIds: ['the-accountant', 'midas-touch'],
    description: 'Each property generates 50 coins at round end. Passive income king.',
    icon: '💰',
  },
  {
    id: 'cursed-fortune',
    name: 'Cursed Fortune',
    requiredCharmIds: ['debt-collector', 'golden-handcuffs'],
    description: 'Rent income is tripled. You can\'t sell, but you don\'t need to.',
    icon: '☠️',
  },
  {
    id: 'high-roller',
    name: 'High Roller',
    requiredCharmIds: ['the-gambler', 'double-down'],
    description: 'Gambler payout doubled to +600/-400. Fortune favours the bold.',
    icon: '🎲',
  },
  {
    id: 'lucky-amplifier',
    name: 'Lucky Amplifier',
    requiredCharmIds: ['lucky-charm', 'charm-amplifier'],
    description: 'All charm effects are 25% stronger AND you have extra charm slots.',
    icon: '⚡',
  },
  {
    id: 'all-in-gambler',
    name: 'All In Gambler',
    requiredCharmIds: ['all-in', 'the-gambler'],
    description: 'Gambler can no longer lose coins. All rent and gambler gains doubled.',
    icon: '♠️',
  },
  {
    id: 'discount-developer',
    name: 'Discount Developer',
    requiredCharmIds: ['upgrade-discount', 'house-of-cards'],
    description: 'Upgrades cost 60% less. No more random vanishing upgrades.',
    icon: '🏗️',
  },
  {
    id: 'fate-master',
    name: 'Fate Master',
    requiredCharmIds: ['fate-weaver', 'time-traveller'],
    description: 'Events always help you. Time Traveller can be used twice.',
    icon: '🌠',
  },
  {
    id: 'robber-baron',
    name: 'Robber Baron',
    requiredCharmIds: ['the-parasite-estate', 'rubber-baron'],
    description: '10% of all rent on the board flows to you, plus 2 coins per opponent coin spent.',
    icon: '🎩',
  },
];

export const RARITY_COLORS: Record<string, string> = {
  Common: '#9CA3AF',
  Uncommon: '#10B981',
  Rare: '#3B82F6',
  Epic: '#8B5CF6',
  Legendary: '#F59E0B',
  Cursed: '#EF4444',
};

export function getCharmDef(id: string): CharmDefinition | undefined {
  return ALL_CHARMS.find((c: CharmDefinition) => c.id === id);
}

/** Get the upgrade cost for a charm at a given level */
export function getCharmUpgradeCost(def: CharmDefinition, currentLevel: number): number {
  if (!def.upgradeable || currentLevel >= (def.maxLevel ?? 1)) return Infinity;
  // Each level costs 60% of base cost * level
  return Math.floor((def.cost ?? 100) * 0.6 * currentLevel);
}
